### ISSUE TITLE
legend label turns to 0 in pie/donut chart with only one category

### ISSUE THREAD

**Issue by zhiboz** [mrjoh3/c3#3]
the legend label turns to '0' in pie/donut charts with only one category, see the sample code below.

```
data.frame(red=82) %>% 
  c3() %>% 
  c3_pie()
```

```
data.frame(red=82) %>% 
  c3() %>% 
  c3_donut()
```

**Comment by mrjoh3** [comment]
hi @zhiboz, I had not considered such a use case but the single value broke the R to js data structure translation. This should now be resolved but please check and advise if you have any problems.

**Comment by zhiboz** [comment]
it works beautifully now. thanks a ton!
