### ISSUE TITLE
How to add Onclick event to chart?

### ISSUE THREAD

**Issue by mishaborys** [mrjoh3/c3#6]
I want to add onclick event to chart in Shiny App. I`v read [this article with c3 examples ](https://shiny.rstudio.com/articles/js-send-message.html)and try to do some simple app with print in console when clicked on chart. But in my case, onclick I have [this error in console](https://i.stack.imgur.com/6R63A.png). Could you, please, say what I do wrong?
```
    library(c3)
    library(shiny)

    shinyApp(
        ui = fluidPage(
            c3Output("c3test")
        ),
        server = function(input, output, session) {
          output$c3test <- renderC3({
            pie.chart <- data.frame(sugar=20,fat=45,salt=10) %>% 
              c3(onclick="function(d,element) {
                 console.log(d.id);
          }") %>% 
                    c3_donut()
        })
        }
    )
```

**Comment by mrjoh3** [comment]
you are very close. You just need to wrap your js function in JS. Have a look at Issue #4 had where another user had the same same problem. 

```
c3(data, onclick = htmlwidgets::JS('function(d, element){console.log(d.id)}'))
```

**Comment by mrjoh3** [comment]
commit e2bea1c20b56ac7affad10a42fe52d3fe8615dd6 added an example to the readme page and to the `c3()` functions documentation

**Comment by mishaborys** [comment]
Thanks a lot for fast feedback. It really help me.
